# Generated by Django 3.0.6 on 2020-05-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ins', '0002_auto_20200531_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
